### ISSUE TITLE
Raiden Docs must be up to date with respect to the Raiden Wizard

### ISSUE THREAD

**Issue by Dominik1999** [raiden-network/raiden-wizard#101]
We need to update the docs, when we have the Raiden Wizard finalized.

We need to 
- [x] Update the [current docs](https://docs.raiden.network/quick-start) with the new Wizard content. Make sure to emphasize that this is only available on Mainnet for now
- [x] We need that lovely gif for the new Wizard
- [x] We need to explain the prerequisites (having Metamask and Infura) somewhere in the docs
- [x] ...

**Comment by Dominik1999** [comment]
Talel will help us and we need to tell him beforehand

**Comment by Dominik1999** [comment]
We need to 
- [ ] Update the [current docs](https://docs.raiden.network/quick-start) with the new Wizard content. Make sure to emphasize that this is only available on Mainnet for now
- [ ] We need that lovely gif for the new Wizard
- [ ] We need to explain the prerequisites (having Metamask and Infura) somewhere in the docs
- [ ] ... 

@taleldayekh May I ask you to help us here?

**Comment by taleldayekh** [comment]
Sure, @dominik, I’ll help with that.

**Comment by konradkonrad** [comment]
@Dominik1999 what is
> - [ ]  We need that lovely gif for the new Wizard

referring to?

**Comment by Dominik1999** [comment]
to the gif here in https://docs.raiden.network/quick-start

**Comment by konradkonrad** [comment]
@Dominik1999 
So that part is already done?

**Comment by Dominik1999** [comment]
No, that is the old Wizard for the testnet. We need to replace the text and the video with the new Wizard

**Comment by konradkonrad** [comment]
@taleldayekh can you create such a gif?

**Comment by konradkonrad** [comment]
Updated the docs with revision https://github.com/raiden-network/raiden-documentation/commit/04bdb3db5f18af9d7ff6ec02406ccf1e71ef01b9
**Missing:** 
- [ ] Current walkthrough GIF 

@taleldayekh can you provide that?

**Comment by taleldayekh** [comment]
I'll start with the gif tomorrow. Need to run through the mainnet Wizard and make a recording. @Dominik1999 guess you can help with the dollars for this?
