### ISSUE TITLE
Swapping ETH to Tokens takes either a long time or never completes

### ISSUE THREAD

**Issue by agatsoh** [raiden-network/raiden-wizard#105]
This is regarding the interface on Raiden Wizard which swaps ETH with other Tokens like RDN, DAI etc for user onboarding. According to my recent experiences on the mainnet while exchanging ETH for RDN 
1. Kyber takes around 15+ mins approx time to swap ETH for RDN tokens 
2. Uniswap unfortunately never returns and times out, the spinner going on indefinitely

We need to examine why the APIs take such a long time for the swap and either introduce and alternative or stick to only one which works.
- [ ] Identify why Kyber takes such a long time
- [ ] Identify why Uniswap never completes the swap
- [ ] Identify alternatives to kyber and uniswap and implement their API's in Raiden wizard.

**Comment by Dominik1999** [comment]
duplicate to #99
