### ISSUE TITLE
Refactoring of the Wizard Code

### ISSUE THREAD

**Issue by Dominik1999** [raiden-network/raiden-wizard#108]
@konradkonrad updates this issue Mon 27th April

## Helping Mainnet User to start Raiden
The Raiden Wizard should help Mainnet User to start Raiden in 5 steps:

1. Wallet is to be created for the user that must be manually funded with ETH
2. ETH will be swapped the RDN
3. ETH will be swapped to DAI
4. RDN will be deposited into the UDC (Allowance must be set)
5. Raiden is started with pfs routing mode on mainnet

## Refactoring goals
The Wizard has many functionalities and settings that are not needed anymore. 
- There will be no other tokens than DAI and RDN on mainnet
- There will be no nightly and no RC used (Although we might need to test the Wizard with an RC)
- The user should not decide anything but which DEX to be used 
- Decide if integrating Wizard into Raiden Repo?!

## Refactoring steps
- [ ] remove all logic that decides on the network, see https://github.com/raiden-network/raiden-wizard/blob/master/raiden_installer/network.py
- [ ] remove all logic that decides on the token (we only use DAI and RDN), see https://github.com/raiden-network/raiden-wizard/blob/master/raiden_installer/tokens.py
- [ ] remove predefined contract addresses in https://github.com/raiden-network/raiden-wizard/blob/f2a404c442bafd9f38db023ca8a89b98db63d93b/raiden_installer/base.py#L58
- [ ] remove predefined pfs address (should be chosen from registry) in https://github.com/raiden-network/raiden-wizard/blob/f2a404c442bafd9f38db023ca8a89b98db63d93b/raiden_installer/base.py#L68 
- [ ] Environment-Type will only be production https://github.com/raiden-network/raiden-wizard/blob/f2a404c442bafd9f38db023ca8a89b98db63d93b/raiden_installer/base.py#L80
- [ ] ...

## Wizard on the Demo-Environment
Since we also want to have a Raiden Wizard on the Demo-Environment, we will have two branches of the Raiden Wizard that we can merge again later.

**Comment by christianbrb** [comment]
It should be quite straight forward:

If goerli -> use testnet code and front-end
If mainnet -> use mainnet code and front-end

A lot of portions of the code should work for mainnet and testnet.

|Function   |Mainnet   |Testnet   |
|:-:|---|---|
|Wallet is to be created   |x   |x   |
|funded with ETH   |manually   |faucet   |
|RDN   |Swapped with ETH   |SVT minting   |
|DAI   |Swapped with ETH   |WIZ? minting   |
|RDN Deposit   |x   |x   |
|Start RDN   |Mainnet parameters   |testnet parameters   |

@jomuel @eorituz Isn't the code already structured that way?

**Comment by Dominik1999** [comment]
It doesn't quite look like it. There is a lot of code and hardcoded values that are not needed and need to be maintained.

We do not need to know if there is a faucet available in a network almost this whole file is not needed

- https://github.com/raiden-network/raiden-wizard/blob/master/raiden_installer/network.py

This automatic (and highly complicated / hard coded) way of getting the right Raiden version is not needed here, we don't want people to use the Raiden Wizard with an RC or even a nightly. If there will be only one version used, the code is much simpler, see last 100 lines

- https://github.com/raiden-network/raiden-wizard/blob/master/raiden_installer/raiden.py

We don't need to hardcode any tokens and maintain that. We only need RDN and DAI. The whole file might be obsolete
- https://github.com/raiden-network/raiden-wizard/blob/master/raiden_installer/tokens.py

Minting and recalculating tokens will be obsolete, also automatically getting the ServiceToken looks buggy. We know the token address of RDN
- https://github.com/raiden-network/raiden-wizard/blob/master/raiden_installer/transactions.py
- https://github.com/raiden-network/raiden-wizard/blob/master/raiden_installer/account.py

Looking at the time we have left, I suggest deleting everything that is not used on mainnet for Alderaan. We can then add functionality afterwards if needed

**Comment by christianbrb** [comment]
Ok, thanks for the detailed feedback :) We can also do merging the code after go-live and keep the current version as a separate branch for testnet.

**Comment by Dominik1999** [comment]
Code changed a lot. We still need to refactor, but we will open separate issues
