### ISSUE TITLE
Check transaction handling of the Wizard and align with Raiden libs

### ISSUE THREAD

**Issue by Dominik1999** [raiden-network/raiden-wizard#112]
The Raiden Wizard should use well tested and elaborated code when transacting with the blockchain. 

- [ ] check how transactions to the blockchain are being done in the Wizard
- [ ] compare to how it is done in the Raiden client
- [ ] align the Wizard to client transaction handling

**Comment by Dominik1999** [comment]
So can we close this issue?

**Comment by fredo** [comment]
yes we can.
