### ISSUE TITLE
Document configuration elements

### ISSUE THREAD

**Issue by konradkonrad** [raiden-network/raiden-wizard#115]
We need transparency over the configuration elements of the wizard.

Document which configuration parts are stored/templated where:
- browser + addresses
- configuration for wizard steps (web3, funding, contracts)
- raiden flags for launch

The assumption is, that there are unclear boundaries between the configurations.

**Comment by fredo** [comment]
It seems that the whole `RaidenConfigurationFile` object gets passed to raiden upon start. Also the above mentioned options such as `keystore-file-path` which is not a valid option running raiden which leads to a crash upon starting raiden
