### ISSUE TITLE
Wizards starts WebUI when API not yet ready

### ISSUE THREAD

**Issue by fredo** [raiden-network/raiden-wizard#117]
The WebUI is started before the Raiden API is ready. It works after a minute but it is not very nice first thing to see is an API error in the webui.

The WebUI is reachable while the RestAPI in raiden is not started yet. This causes the errormessage shown.

**Comment by fredo** [comment]
Use the status endpoint as a trigger to start the webUI

**Comment by Dominik1999** [comment]
- [ ] Query status endpoint of Raiden and start WebUI after Raiden ist ready
- [ ] This doesn't really fixes the problem, we need to get the UI / UX designers on that

**Comment by konradkonrad** [comment]
Note: #124 fixes the start timing of the WebUI, by polling the [`/status` api](https://raiden-network.readthedocs.io/en/latest/rest_api.html#querying-node-state) for a `{"status": "ready"}` response.

However, before that response, the same API can be used to return
```
{
   "status": "syncing",
   "blocks_to_sync": "130452"
}
```
which can (and probably should) be displayed on the waiting page.
