### ISSUE TITLE
Move configurable constants to a central location

### ISSUE THREAD

**Issue by konradkonrad** [raiden-network/raiden-wizard#122]
Currently there are configuration related constants scattered all over the project. We should invest some time to identify global configuration values and move them to a central location. As an example:
- [`GAS_PRICE_MARGIN`](https://github.com/raiden-network/raiden-wizard/pull/121/files#diff-2185bdc7e8f1d2bc347c9c2b287a6bf9R76)
- [`CMC-API_KEY`](https://github.com/raiden-network/raiden-wizard/pull/119/files/34379c114b64ec40f55988286748ed9f346d7b85#diff-8a167d9dda5a229cbca7911ae29f43ebR120)

**Comment by manuelwedler** [comment]
I think this can be considered as done. Closing
