### ISSUE TITLE
Swapping DAI at uniswap is not possible

### ISSUE THREAD

**Issue by Dominik1999** [raiden-network/raiden-wizard#141]
We need to add DAI to be exchangeable at uniswap.

**Comment by manuelwedler** [comment]
The exchange address needs to get added here: https://github.com/raiden-network/raiden-wizard/blob/89f33a3c44414ef151719c995d722340d144e322/raiden_installer/token_exchange.py#L220

**Comment by Dominik1999** [comment]
and please change SAI to DAI

**Comment by Dominik1999** [comment]
check if version 2 changes addresses

**Comment by agatsoh** [comment]
> Uniswap V2 is currently in a testnet release, and is slated to be deployed to mainnet in 2020 Q2, pending a successful formal verification. Looking for V1 documentation?

https://uniswap.org/docs/v2/

So we might still need to go with version 1

**Comment by agatsoh** [comment]
DAI is abled  to be Swapped with Uniswap at the moment but gas estimation needs some work hence closing this.
