### ISSUE TITLE
Give better Feedback to the user when exchange is in progress

### ISSUE THREAD

**Issue by fredo** [raiden-network/raiden-wizard#161]
When the exchange is in progress the user gets partially unnecessary and partially false information. 

We add a specific margin on top of gas price and gas limit, as well as for kyber we must send more eth than necessary to receive the exact expected amount. All of these increase the estimated costs. But this is not what the user ends up paying. SoIMO it would be better to let him know that the user is not paying more than the used amount. But most likely less. 
Also a better visualization of the values would be nice. Currently we show the rate which the user is most likely to get (not fixed rate). This is a value hard to understand (TWEI). Then the conclusion of estimated costs to the Rate does not fit since we send extra margins and the transaction cost is included in the estimated costs as well.

**Comment by agatsoh** [comment]
We can use this issue to track the summary page that we are going to create after each swap.
