### ISSUE TITLE
Inform user about the high 0.11 ETH requirement.

### ISSUE THREAD

**Issue by agatsoh** [raiden-network/raiden-wizard#176]
The 0.18 ETH requirement for the user is quite high which translates to around 36 to 40 $. Most of the other Dapps in the Ethereum space do not have such high barrier to entry. Hence we need to inform the user justifying such a high price to run raiden.

**Comment by Dominik1999** [comment]
We agreed now to a lower ETH requirement of 0.11 ETH, see https://github.com/raiden-network/raiden-wizard/issues/205#issuecomment-628072476

But we still need to inform the user.

**Comment by Dominik1999** [comment]
closed by #226
