### ISSUE TITLE
Remove dead code

### ISSUE THREAD

**Issue by konradkonrad** [raiden-network/raiden-wizard#199]
We should delete any unused code. While writing the tests for the whole Wizard (#216 & #217) it should be easy to check which parts of the code are not needed anymore.

**Comment by manuelwedler** [comment]
While writing tests I will check for dead code and remove it. 
Regarding the initial issue definition: The `PassphraseFile` will be used again when the Goerli Wizard generates a random password again (#282). I updated the issue description.

**Comment by manuelwedler** [comment]
I have gone through the whole codebase now and removed dead code.  Closing
