### ISSUE TITLE
Make the Swap Summary be more present for the user

### ISSUE THREAD

**Issue by fredo** [raiden-network/raiden-wizard#201]
We have a swap summary after every swap to highlight the information if the swap was successful or not and to which page he is going to be redirected. 

For that there is a new web socket message type called `summary`.

This message type clears the page and receives an array of text to print. 

It would be nicer if it is highlighted more and maybe have some icons added (DAI or RDN).
We can discuss the protocoll what information the submitted json needs to contain.

**Comment by Dominik1999** [comment]
Can you share screenshots how it looks atm? @fredo

**Comment by Dominik1999** [comment]
Can you look into this very specific issue @manuelwedler ?

**Comment by manuelwedler** [comment]
Sure, I will do it!

**Comment by fredo** [comment]
![swap_summary](https://user-images.githubusercontent.com/10088275/81709290-1227c400-9472-11ea-9495-72c795940c32.png)

**Comment by fredo** [comment]
Yesterday in the Demo, @taleldayekh missed the screen saying `Congratulations! Swap Successful! Moving on to exchanging DAI`. 

He thought that he was actually back to the screen of exchanging RDN and was confused
