### ISSUE TITLE
Mini - UX edits after feedback 12th of May

### ISSUE THREAD

**Issue by Dominik1999** [raiden-network/raiden-wizard#208]
We have a bunch of Mini-UX edits that can be "abgefrühstückt" in one PR.

- [x] Text should always be bigger than 12pt 
- [ ] Text and Spinner are a bit too close
- [ ] Have different colours for amounts of tokens and the text (e.g. when swapping)
- [x] Always put the Step Number in the title of the page
- [x] Adjust text on page 2 (Just write "Enter your Infura ID that will connect you to the Ethereum Blockchain")
- [x] Whenever "Raiden" is mentioned, write it in upper case
- [x] Never use "Wallet" always "Raiden Account"
- [ ] Allow user to see the passphrase when she chooses it for her ~~wallet~~ Raiden Account. Include an Eye-Symbol. 
- [ ] Convert ETH values into a different unit if numbers get too small

**Comment by Dominik1999** [comment]
Closing this for now, we have a codefreeze. Follow up issue #256

**Comment by agatsoh** [comment]
Show password eye symbol solved by 
https://github.com/raiden-network/raiden-wizard/pull/258
