### ISSUE TITLE
We need to handle a failing tx 

### ISSUE THREAD

**Issue by Dominik1999** [raiden-network/raiden-wizard#209]
In the demo of the 12th of May we had a transaction that was way underpriced. The user has no info what to do and the Wizard cannot handle this situation.

I as a user would want to get informed when a transaction takes longer than 1 minute. If this happens I need to have options how to handle that. One option could be to speed up the transaction. ATM the Wizard does not detect that new transaction.

**Comment by konradkonrad** [comment]
### Gameplan: 
On initial funding
- record the txhash of the initial ETH funding by saving it into the configuration file as `initial_funding_txhash`
- IF the ui times out when waiting for the tx, we will **shut the wizard down**

When starting with an **existing** configuration file
- check IF `initial_funding_txhash` exists
- WHEN found by rpc-client and NOT yet mined show message to user

> It seems the ETH funding for your Raiden Wallet takes a long time. You can watch the state of the transaction at etherscen [link to txhash on etherscan]

and wait again on the tx.
- WHEN found by rpc-client and mined proceed to swap page
- WHEN not found by rpc-client delete txhash from configuration file and proceed to initial ETH funding

**Comment by Dominik1999** [comment]
awesome!
