### ISSUE TITLE
Place a tooltip on every page at the same place - with 4 placeholder bullets 

### ISSUE THREAD

**Issue by fredo** [raiden-network/raiden-wizard#213]
On every page we show different information to explain why he is doing what he is doing and hints to often raised questions. 

Currently on each page we are answering the question differently. This leads to the fact that often the answers to the questions are overseen because they are not prominent enough. 

For example: 

- When the infura ID is required we have a little information icon
- When sending ETH we have a tooltip on `Raiden account` explaining what a raiden account is and a plain text at the center of the page telling the user to download the account
- When swapping RDN or DAI we have a tooltip on the text `RDN` or `DAI` which explains why we need the token and how much is required. This is always overseen and these questions are always raised
- We also need to explain in the beginning why the user is required to deposit a specific amount of eth and what he is going to do 

I think a consistent design throughout all the pages answering FAQs for each page would help the user to know where to look for questions. We have a lot of free space on the screen and we should use it IMO. 

@sashseurat  Can you help on this?

**Comment by Dominik1999** [comment]
see if #214 helps? I have the feeling that we need to explain the user at the beginning what he is going to do and why

**Comment by sashseurat** [comment]
> On every page we show different information to explain why he is doing what he is doing and hints to often raised questions.
> 
> Currently on each page we are answering the question differently. This leads to the fact that often the answers to the questions are overseen because they are not prominent enough.
> 
> For example:
> 
> * When the infura ID is required we have a little information icon
> * When sending ETH we have a tooltip on `Raiden account` explaining what a raiden account is and a plain text at the center of the page telling the user to download the account
> * When swapping RDN or DAI we have a tooltip on the text `RDN` or `DAI` which explains why we need the token and how much is required. This is always overseen and these questions are always raised
> * We also need to explain in the beginning why the user is required to deposit a specific amount of eth and what he is going to do
> 
> I think a consistent design throughout all the pages answering FAQs for each page would help the user to know where to look for questions. We have a lot of free space on the screen and we should use it IMO.
> 
> @sashseurat Can you help on this?

I'll gladly help, but this issue requires time, so we need to figure out if I can dedicate time to this over other things.
I can ask Kamal

**Comment by Dominik1999** [comment]
For the first iteration, we do not have that much time, so we will go for a quick solution. 

My suggestion now is to 

- provide background information for every one of the 6 steps / page
- have an icon that opens a tooltip that explains the step
- try to explain every step in only four bullets

Does that make sense to you @Fred?

**Comment by fredo** [comment]
Yes. I think as we already got feedback, we got a lot of free sapce in the screen so we can use it. Im gonna create an issue containing all the questions/answers for each page

**Comment by Dominik1999** [comment]
Maybe just add those bullets per page here in this issue to reduce a little bit of noise

**Comment by konradkonrad** [comment]
- [ ] for now: trigger a "you should stay on this page" alert
