### ISSUE TITLE
UX explain the flow of the 6 steps

### ISSUE THREAD

**Issue by Dominik1999** [raiden-network/raiden-wizard#214]
# We want to make the user understand the process on every step
At the moment the user does not quite understand the reasons for the different steps. We want to better explain and guide the user in the Wizard.

Therefore, we want to 
- explain to the user why the Wizard is needed on the first page and
- use a progress bar as a headline 

For the progress bar, 

- [x] find a suitable icon for the wallet that we can use (we can also pay for that)
- [x] find a suitable icon for the connecting step that we can use (we can also pay for that)

## Start-Page (disclaimer)

![Disclaimer-Page](https://user-images.githubusercontent.com/35031754/81809363-8a998e00-9521-11ea-9386-56e8622c2e37.jpg)

- [x] Show this graphic on the first page 

## Progress bar on pages 2-7
![](https://lh3.googleusercontent.com/proxy/oLjeWcLsmH9rSi-cfa_w30L8LqgK8veBaRpi48Td-zsETmFffEendtE7XuLk9TyfDWiel4gVgrZPC3m9bSC8_74VXncKTBAz8Biry0F8eJ45J5iUn8Rsj44Viehf)
- [x] Remove existing ticker
- [x] Use a progress bar that suits the style consisting of 6 steps 
- [x] Page 2 should show the wallet icon in step 1 of the progress bar and `Create a Raiden Account` as a headline under the progress bar
- [x] Page 3 should show the connecting icon in step 2 of the progress bar and `Connect to the Ethereum Blockchain` as a headline under the progress bar
- [x] Page 4 should show the ETH icon in step 3 of the progress bar and `Fund Account with ETH` as a headline under the progress bar
- [x] Page 5 should show the RDN icon in step 4 of the progress bar and `Fund Account with RDN` as a headline under the progress bar
- [x] Page 6 should show the DAI icon in step 5 of the progress bar and `Fund Account with DAI` as a headline under the progress bar
- [x] Page 7 should show the Raiden Ball icon in step 6 of the progress bar and `Launch Raiden` as a headline under the progress bar

![Raiden Ball](https://user-images.githubusercontent.com/35031754/81814255-d4d23d80-9528-11ea-89fe-f4637c872a8c.jpg)

- [x] When the user clicks on "launch" show the Raiden Video on full screen

[Raiden Video Launch.zip](https://github.com/raiden-network/raiden-wizard/files/4621759/Raiden.Video.Launch.zip)

**Comment by ulope** [comment]
Maybe incorporating the icons into a progress bar can make it even clearer.
Something like this: 
![](https://lh3.googleusercontent.com/proxy/oLjeWcLsmH9rSi-cfa_w30L8LqgK8veBaRpi48Td-zsETmFffEendtE7XuLk9TyfDWiel4gVgrZPC3m9bSC8_74VXncKTBAz8Biry0F8eJ45J5iUn8Rsj44Viehf)

**Comment by konradkonrad** [comment]
Agree with @ulope here -- such a progress bar could later also function as a "breadcrumb" navigation.

**Comment by Dominik1999** [comment]
makes total sense, let's do that with a progress bar
