### ISSUE TITLE
Offer a platform where to download a final wizard binary

### ISSUE THREAD

**Issue by fredo** [raiden-network/raiden-wizard#225]
We need to offer a download link or some platform where a zipped binary of the release wizard is published, so that this link can be promoted

**Comment by Dominik1999** [comment]
I think last time we simply used the Github Release Page and informed people via a blogpost

**Comment by fredo** [comment]
lets do this. with `make bundle-docker` we can create an already zipped binary for linux. Im gonna close this issue
