### ISSUE TITLE
0.11 ETH might not seem enough

### ISSUE THREAD

**Issue by fredo** [raiden-network/raiden-wizard#234]
While testing I usually end up with 0.07 ETH which is not enough to join the network with 3 channels. 

Maybe we should increase it a little bit. My suggestion: **0.125** ETH which is then roughly a buffer of 0.01 ETH which covers price fluctuations and transaction fees for a while. 

@Dominik1999 what do you think?

**Comment by Dominik1999** [comment]
good idea
