### ISSUE TITLE
Video stops playing when Raiden is being launched / missing user feedback

### ISSUE THREAD

**Issue by fredo** [raiden-network/raiden-wizard#239]
When launching Raiden, the video stops playing and there is no message for the user. For the user it might seem that the wizard stopped running. 

It would be nice to have the video running until the WebUI is launched and maybe a little text whats happening right now (Like it was before)

**Comment by fredo** [comment]
the video still does not start for me on brave

**Comment by manuelwedler** [comment]
Oh no. that's bad. I will have a look tomorrow morning.
