### ISSUE TITLE
No MetaMask text is only displayed after clicking download twice

### ISSUE THREAD

**Issue by manuelwedler** [raiden-network/raiden-wizard#240]
When no MetaMask is installed we link to the MetaMask website to download it. The user has to click the download button twice at the moment for the link to be shown. It should be displayed after on click like the Send ETH button.

**Comment by fredo** [comment]
The same happens to me for the send eth button sometimes

**Comment by fredo** [comment]
This should be fixed by #250. Am I right @konradkonrad?

**Comment by konradkonrad** [comment]
If my guess on what happened here is correct, it should be fixed now:

https://github.com/raiden-network/raiden-wizard/pull/250/files#diff-7d08051fd4f29cfe45135ba82554211a

changes the download button to only appear, once the js logic is ready

**Comment by manuelwedler** [comment]
I can confirm that this is fixed. Closing.
