### ISSUE TITLE
Kyber throwing errors due to low liquidity

### ISSUE THREAD

**Issue by BOR4** [raiden-network/raiden-wizard#269]
Happened to one of the community members:

raiden_installer.token_exchange.ExchangeError: Trade not possible at the moment due to lack of liquidity

**Comment by palango** [comment]
Can we disable the button when no liquidity is available?

**Comment by fredo** [comment]
Im not sure how we can check in advance if there is enough liquidity before having a failed transaciton. @BOR4  Do you have some logs ?

**Comment by BOR4** [comment]
sorry I don't. I just picked it from tg chat.
But if you go to https://kyberswap.com/limit_order/rdn-weth you will see something about maintenance. Not sure why is that.
 
![image](https://user-images.githubusercontent.com/40821065/83752077-312c0700-a668-11ea-8726-71b3ca2140df.png)

**Comment by Dominik1999** [comment]
Kyber refinances via Binance which has removed the ETH RDN trading pair two weeks ago. ATM we cannot do more than remove Kyber from the RDN swap page in the Wizard, see #271
