### ISSUE TITLE
RDN (and maybe DAI?) balance is not recognized by the script

### ISSUE THREAD

**Issue by nrgskill** [raiden-network/raiden-wizard#273]
If you deposit 10 RDN while the wizard is running, the program won't recognize the new balance and will keep asking to purchase. After the purchase is will lock the total amount:
On mainnet,
-start wizard with new address
-deposit 0.125 ETH
-continue to the RDN purchase page
-send to the address 10 RDN and wait for confirmations
-try to move back to the previous screen (eth)
-proceed to the RDN screen:
**the newly deposited RDN are not recognized, the script keeps asking for conversion**
-proceed with the conversion (now you have 20 RDN)
-the script will lock the total amount in the wallet (20 RDN)

didn't try with DAI

**Comment by Dominik1999** [comment]
Hey @nrgskill thanks for creating this issue!

Were those RDN tokens already deposited into the UDC or were those still on your account?

**Comment by agatsoh** [comment]
Hello @nrgskill just to confirm this `address ` that you send the RDN to is the newly generated raiden account right ?

**Comment by nrgskill** [comment]
> Hello @nrgskill just to confirm this `address ` that you send the RDN to is the newly generated raiden account right ?
If for raiden account you mean the newly generated eth address, then yes. Tokens were just sent to it, not into the contract. The script should see them in the address (instead of presenting you with the purchase screen) and move forward to add them into the contract

**Comment by manuelwedler** [comment]
solved by #301
