### ISSUE TITLE
Channel with 0x2222222222222222222222222222222222222222

### ISSUE THREAD

**Issue by pirapira** [raiden-network/raiden-wizard#30]
After I run the installer, I saw a channel with address 0x2222222222222222222222222222222222222222.

This might be
* somebody opened a channel between this address and me (with no hope of 0x222.222 ever making a valid transaction)
* or the interface is showing a channel that does not exist.

Either way it's weird.

**Comment by kelsos** [comment]
Isn't that the "boostrap address" of the connection manager? https://github.com/raiden-network/raiden/blob/d0f88a3d3405c3eba6cb9158dfc13a9cc333fbd6/raiden/connection_manager.py#L71

**Comment by pirapira** [comment]
@kelsos I see.  That's then a dummy that shouldn't be used ever, so maybe hide from users?

**Comment by agatsoh** [comment]
We dont see this any longer so we should close this issue now.
