### ISSUE TITLE
CRITICAL - RDN swap broken

### ISSUE THREAD

**Issue by manuelwedler** [raiden-network/raiden-wizard#308]
It is not possible to trade RDN anymore.

- There is almost no liquidity for RDN on uniswap v1. We should move to v2 now.
- Kyber delisted RDN. We should consider to use a different exchange for the swap as we might need to have two.

Tasks:

- [x] Upgrade to Uniswap v2
- [ ] Decide on what to do about Kyber
- [ ] ...

**Comment by christianbrb** [comment]
Isn't this already fixed?

**Comment by manuelwedler** [comment]
Uniswap v2 is working, so it is possible to swap RDN tokens. But the question now is if we can leave it without a second option for swapping RDNs, because there were legal reasons for having two exchanges. 
If we can have just one exchange I would remove Kyber from the RDN screen as it will always show an error.
