### ISSUE TITLE
Wizard executable not marked executable

### ISSUE THREAD

**Issue by christianbrb** [raiden-network/raiden-wizard#33]
#### System
Pretty clean Ubuntu 18.04.1 LTS

#### Error-Message
![grafik](https://user-images.githubusercontent.com/35398162/61884002-b9dfff80-aefb-11e9-8472-e23303e48327.png)

**Comment by ulope** [comment]
The executable inside the archive is missing the executable flag.

**Comment by fredo** [comment]
included in #225
