### ISSUE TITLE
Non-technical users will have a hard time stopping Raiden

### ISSUE THREAD

**Issue by ulope** [raiden-network/raiden-wizard#37]
The Raiden instance launched from the wizard is hard to stop for non technically / terminal savvy users.

**Comment by karlb** [comment]
We could add a "stop raiden" RPC endpoint add a way to call it to the WebUI.

**Comment by ulope** [comment]
We would need to think about the security implications of adding a stop endpoint. 

But even just via normal OS process tools should be realatively easy.

**Comment by karlb** [comment]
> We would need to think about the security implications of adding a stop endpoint.

We have endpoints to send tokens around. I don't think the stop end point is any more security critical.

**Comment by ulope** [comment]
True, but Jacob and I were thinking about the publicly hosted test / workshop nodes for example. It's no big problem if their channels get drained but shutting them down continually makes them unusable with very little effort on an attackers part.

**Comment by Dominik1999** [comment]
should be solved inhttps://github.com/raiden-network/raiden/issues/6113

**Comment by fredo** [comment]
create a follow up issue for the web UI button

**Comment by Dominik1999** [comment]
https://github.com/raiden-network/raiden/issues/6113 is done now, we can inlcude a `shut down` button into the WebUI.

Can you implement that @manuelwedler ? @christianbrb ?

**Comment by manuelwedler** [comment]
Yes sure. I created an issue in the webui repo: https://github.com/raiden-network/webui/issues/389
I will align with @sashseurat on it.

**Comment by Dominik1999** [comment]
Closing this issue, since we have an issue in the WebUI now
