### ISSUE TITLE
Raiden Wizard for Mainnet

### ISSUE THREAD

**Issue by Dominik1999** [raiden-network/raiden-wizard#48]
We need to upgrade the Raiden Wizard for the mainnet. 
Therefore the token minting for testnet needs to be replaced by integration of two DEXes - Uniswap and Kyber (see [here](https://docs.google.com/document/d/13iIkGFAC6d-Q6wd8jf56tkHTc8PCdQGNI9TLKnIIXOI/edit))

We need this until 16.09.

Please refine the specific steps and post it here.

**Comment by jomuel** [comment]
There is a project now to implement the mainnet functionality in the new version until mid April:
https://github.com/raiden-network/raiden-wizard/projects/2
