### ISSUE TITLE
wizard is stuck on first run

### ISSUE THREAD

**Issue by BOR4** [raiden-network/raiden-wizard#59]
I just started normal installation:
error from console:
![image](https://user-images.githubusercontent.com/40821065/64726160-52dfcf80-d4d6-11e9-8652-bd247594edbc.png)

**Comment by BOR4** [comment]
![image](https://user-images.githubusercontent.com/40821065/64728542-7b1dfd00-d4db-11e9-9934-85abe4b091fa.png)


(this is from second try but error was same on the first try)

**Comment by jomuel** [comment]
Closing this as I haven't seen it happening since I took over from @lullis, and the installer has been mostly rewritten since this was reported. @BOR4, please let me know if it is still a problem.
