### ISSUE TITLE
Running latest version on WSL (Windows Linux Subsystem) fails

### ISSUE THREAD

**Issue by christianbrb** [raiden-network/raiden-wizard#63]
# Steps to reproduce the issue

## Install WSL (Windows Linux Subsystem)
Follow thi or another guide to install the WSL on Windows 10
https://linuxhint.com/install_ubuntu_windows_10_wsl/

## Run Ubuntu
Just enter "Ubuntu" in your quick start search.

## Download Wizard

```
curl -LO https://github.com/raiden-network/raiden-installer/releases/download/v0.32.0-testnet/raiden_wizard.linux-gnu.bin.tar.gz
```

## Extract Wizard

```
tar -xvzf raiden_wizard.linux-gnu.bin.tar.gz
```

## Run the Wizard

```
./raiden_wizard.linux-gnu.bin
```

## Access the Wizard
Open

http://127.0.0.1:8888/

in your browser

## Execute the Wizard

Follow the [guide starting with 2.](https://docs.raiden.network/quick-start#setup-and-run-a-raiden-node)

## Error

`Failed to add funds to account: HTTPSConnectionPool(host='goerli.infura.io', port=443): Max retries exceeded with url: /v3/f1f227986cc5496a965fb9a499eed13e (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f108f3975f8>: Failed to establish a new connection: [Errno 16] Device or resource busy'))`

**Comment by christianbrb** [comment]
Full [error logs](https://gist.github.com/christianbrb/ec7c43fa43ddb8bfb8c9c4ebe9039712)

**Comment by jomuel** [comment]
According to @christianbrb this does not affect the current version of the wizard anymore.
