### ISSUE TITLE
Make it easier to find the agree check box on the first page

### ISSUE THREAD

**Issue by hackaugusto** [raiden-network/raiden-wizard#82]
The initial page has a terms and conditions check box, which is bellow the first button, depending on the user's screen resolution is possible for this checkbox to be "hidden", requiring scrolling by the user.

A nice fix would be to change the text in the button to "Agree with terms and conditions" and make the screen responsive.

At the very minimum the checkbox should use the text as a label, and the text should be more visible.

**Comment by manuelwedler** [comment]
The checkbox is now above the button and the text is reduced. The user should be able to find the checkbox easily. Closing
