### ISSUE TITLE
Check Configuration of DEX transactions and optimize

### ISSUE THREAD

**Issue by Dominik1999** [raiden-network/raiden-wizard#99]
## Check if Raiden uses optimal transaction settings to swap tokens
Since the Raiden Wizard will be the Raiden business card, it must be easy to use and secure. Despite the main idea being simple the devil might be in the details. There was no analysis of the DEX integration so far. One can swap tokens with many different settings, e.g. gas costs and slippage. 

See Advanced Settings when swapping:
- https://kyberswap.com/swap/eth-knc
- https://uniswap.org/

## Basic Flow of the Raiden Wizard
![Raiden Wizard Explain - first page](https://user-images.githubusercontent.com/35031754/79965182-0016bf00-848c-11ea-9f60-90ab7e8fa3f7.jpg)

**in five steps**

![Raiden Wizard Explain - icons](https://user-images.githubusercontent.com/35031754/79962670-a06ae480-8488-11ea-925b-89838015a367.jpg)

## Come up with optimal settings for the DEX transactions
A user will not enter any settings so we must come up with very good default settings.

- [ ] Check current settings and see if it makes sense
- [ ] Specify user-friendly settings for Kyber and UniSwap and test
- [ ] Implement settings 
- [ ] related issue #105 ?

**Comment by fredo** [comment]
The following observations have been made:

- Even the gas price set by web3 (fast) leads to ~ 5 minutes waiting period at kyber swap. doubling the gas price (~0.50$, when tested), reduced the time to be mined down to 30 seconds.
- there is a rate calculation done before the kyber swap which might be obsolete. This costs antoher 30 seconds.
- The kyber exchange transaction returns a bit below 2 SAI. It would be nice to receive the amount asked for
- https://kyberswap.com/swap/eth-knc uses higher gas price thus fast swap
- `web3.wait_for_transaction()` has a 120 seconds timeout. This is the reason that sometimes the UI gets stuck on the turning wheel

**Comment by fredo** [comment]
Todos to solve the problems: 

- [ ] increase the gas price manually by a margin
- [ ] increase the timeout for waiting transactions
- [ ] find the reason to receive exactly the amount of SAI asked for

**Comment by fredo** [comment]
Kyber does exchange for the correct amount now and also fast
